python ../ensemble.py -d ntu60_xsub -n 2
python ../ensemble.py -d ntu60_xsub -n 3
python ../ensemble.py -d ntu60_xsub -n 4
python ../ensemble.py -d ntu60_xview -n 2
python ../ensemble.py -d ntu60_xview -n 3
python ../ensemble.py -d ntu60_xview -n 4
python ../ensemble.py -d ntu120_xsub -n 2
python ../ensemble.py -d ntu120_xsub -n 3
python ../ensemble.py -d ntu120_xsub -n 4
python ../ensemble.py -d ntu120_xset -n 2
python ../ensemble.py -d ntu120_xset -n 3
python ../ensemble.py -d ntu120_xset -n 4
python ../ensemble.py -d kinetics -n 2
python ../ensemble.py -d kinetics -n 3
python ../ensemble.py -d kinetics -n 4