python ../main.py -c ntu60_xsub_j -e -sc -pre
python ../main.py -c ntu60_xsub_b -e -sc -pre
python ../main.py -c ntu60_xsub_jm -e -sc -pre
python ../main.py -c ntu60_xsub_bm -e -sc -pre
python ../main.py -c ntu60_xview_j -e -sc -pre
python ../main.py -c ntu60_xview_b -e -sc -pre
python ../main.py -c ntu60_xview_jm -e -sc -pre
python ../main.py -c ntu60_xview_bm -e -sc -pre
python ../main.py -c ntu120_xsub_j -e -sc -pre
python ../main.py -c ntu120_xsub_b -e -sc -pre
python ../main.py -c ntu120_xsub_jm -e -sc -pre
python ../main.py -c ntu120_xsub_bm -e -sc -pre
python ../main.py -c ntu120_xset_j -e -sc -pre
python ../main.py -c ntu120_xset_b -e -sc -pre
python ../main.py -c ntu120_xset_jm -e -sc -pre
python ../main.py -c ntu120_xset_bm -e -sc -pre
python ../main.py -c kinetics_j -e -sc -pre
python ../main.py -c kinetics_b -e -sc -pre
python ../main.py -c kinetics_jm -e -sc -pre
python ../main.py -c kinetics_bm -e -sc -pre